package com.waiter.server.services.common.exception;

/**
 * Created by shahen on 11/19/14.
 */
public enum ErrorCode {

    MISSED_FIELD,
    FAILED_AUTHENTICATION,
    DATABASE_INTERNAL_ERROR,
    MULTIPART_NEEDED,
    DUPLICATE_EMAIL_USERNAME,
    DUPLICATE_EMAIL,
    INVALID_EMAIL,
    USER_NOT_FOUND,
    PHOTO_NOT_FOUND,
    EVENT_NOT_FOUND,
    BAD_REQUEST,
    WRONG_VERIFICATION_HASH,
    NOT_FOUND,
    IO_EXCEPTION,
    CAN_NOT_CREATE_DIRECTION,
    FAILD_TRANSLATION

}
